name: Run AQAvit 

on:
  workflow_dispatch: # Allows the job to be manually triggered
  jdkBinaryUrl:
        description: 'URL to binary to be tested'     
        required: true
  nativeTestLibUrl:
        description: 'URL to native test libs (if needed)'
        required: false

env:  # Links to the JDK build under test and the native test libs
  USE_TESTENV_PROPERTIES: true
  CUSTOMIZED_SDK_URL: ${{ github.event.inputs.jdkBinaryUrl }}
  NATIVE_TEST_LIBS: ${{ github.event.inputs.nativeTestLibUrl }}
jobs:
  run_aqa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [sanity, extended]
        suite: [functional, openjdk, system, perf]
        include:
          - target: special
            suite: functional

    steps:

    - name: Run AQA Tests - ${{ matrix.target }}.${{ matrix.suite }}
      uses: adoptium/run-aqa@v2
      with: 
        jdksource: 'customized'
        customizedSdkUrl: ${{ env.CUSTOMIZED_SDK_URL }} ${{ env.NATIVE_TEST_LIBS }}
        aqa-testsRepo: 'adoptium/aqa-tests:v0.8.0-release' # Make sure this branch is set to the latest release branch
        build_list: ${{ matrix.suite }}
        target: _${{ matrix.target }}.${{ matrix.suite }}

    - uses: actions/upload-artifact@v2
      if: always() # Always run this step (even if the tests failed)
      with:
        name: test_output
        path: ./**/output_*/*.tap
